packages:
  - packages/*
  - examples/*
catalog:
  effect: ~3.19.14
  "@effect/experimental": ~0.58.0
  "@effect/opentelemetry": ~0.58.0
  "@effect/platform": ~0.94.1
  "@effect/platform-browser": ~0.74.0
  "@effect/platform-node": ~0.104.0
  "@effect/platform-bun": ~0.87.0
  "@effect/rpc": ~0.73.0
  "@effect/sql": ~0.49.0
  "@effect/sql-sqlite-node": ~0.50.0
  "@effect/sql-sqlite-wasm": ~0.50.0
  "@effect/sql-sqlite-react-native": ~0.52.0
  "@effect/vitest": ~0.27.0
  "@effect/wa-sqlite": ~0.2.1
  "@opentelemetry/exporter-trace-otlp-http": ~0.211.0
  "@opentelemetry/api": ~1.9.0
  "@opentelemetry/sdk-trace-base": ~2.5.0
  "@opentelemetry/sdk-trace-node": ~2.5.0
  "@opentelemetry/sdk-trace-web": ~2.5.0
  "@opentelemetry/sdk-metrics": ~2.5.0
  "@types/node": ~24.10.7
  typescript: ~5.9.3
  vite: ~7.3.1
  vitest: ~4.0.17
  "@electric-sql/client": ~1.4.0
  "@electric-sql/pglite": ~0.3.14
  "@electric-sql/pglite-sync": ~0.4.0
  "@electric-sql/experimental": ~5.0.0
  react: ~19.1.0
  react-dom: ~19.1.0
  uuid: ~13.0.0
  msgpackr: ~1.11.8
  fast-check: ~4.5.3
  "@opentelemetry/semantic-conventions": 1.38.0
onlyBuiltDependencies:
  - esbuild
  - better-sqlite3
  - bun
overrides:
  "@electric-sql/client": "catalog:"
  "@electric-sql/pglite": "catalog:"
  "@electric-sql/pglite-sync": "catalog:"
  "@electric-sql/experimental": "catalog:"
  effect: "catalog:"
  "@effect/experimental": "catalog:"
  "@effect/platform": "catalog:"
  "@effect/platform-browser": "catalog:"
  "@effect/platform-node": "catalog:"
  "@effect/platform-bun": "catalog:"
  "@effect/rpc": "catalog:"
  "@effect/sql": "catalog:"
  "@effect/sql-sqlite-node": "catalog:"
  "@effect/sql-sqlite-wasm": "catalog:"
  "@effect/sql-sqlite-react-native": "catalog:"
  "@effect/vitest": "catalog:"
  "@effect/wa-sqlite": "catalog:"
  "@types/node": "catalog:"
  typescript: "catalog:"
  vite: "catalog:"
  vitest: "catalog:"
  uuid: "catalog:"
  msgpackr: "catalog:"
  fast-check: "catalog:"
  "@opentelemetry/api": "catalog:"
  "@opentelemetry/semantic-conventions": "catalog:"
  "@op-engineering/op-sqlite": "15.2.2"
patchedDependencies:
  "@effect/sql-sqlite-react-native": patches/@effect__sql-sqlite-react-native.patch
  "@effect/sql-sqlite-wasm": patches/@effect__sql-sqlite-wasm.patch
nodeLinker: hoisted
