packages:
  - 'packages/*'

catalog:
  effect: ^3.14.5
  "@effect/experimental": ^0.44.5
  "@effect/platform": ^0.80.5
  "@effect/platform-browser": ^0.59.5
  "@effect/platform-node": ^0.76.9
  "@effect/rpc": ^0.55.7
  "@effect/sql": ^0.33.5
  "@effect/vitest": ^0.19.10
  "@types/node": ^22.14.0
  "typescript": ^5.8.2
  "vite": ^6.2.5
  "vitest": ^3.1.1
  "@electric-sql/client": ^1.0.2
  "@electric-sql/pglite": ^0.2.17
  "@electric-sql/pglite-sync": ^0.3.0